/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppFooter: typeof import("./../components/AppFooter.vue")["default"];
    AppLink: typeof import("./../components/AppLink.vue")["default"];
    AppNavigation: typeof import("./../components/AppNavigation.vue")["default"];
    AppPagination: typeof import("./../components/AppPagination.vue")["default"];
    ArticleDetail: typeof import("./../components/ArticleDetail.vue")["default"];
    ArticleDetailComment: typeof import("./../components/ArticleDetailComment.vue")["default"];
    ArticleDetailComments: typeof import("./../components/ArticleDetailComments.vue")["default"];
    ArticleDetailCommentsForm: typeof import("./../components/ArticleDetailCommentsForm.vue")["default"];
    ArticleDetailMeta: typeof import("./../components/ArticleDetailMeta.vue")["default"];
    ArticlesList: typeof import("./../components/ArticlesList.vue")["default"];
    ArticlesListArticlePreview: typeof import("./../components/ArticlesListArticlePreview.vue")["default"];
    ArticlesListNavigation: typeof import("./../components/ArticlesListNavigation.vue")["default"];
    PopularTags: typeof import("./../components/PopularTags.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
